name: github workflow

on:
  workflow_dispatch:
  push:
    branches:
    - gh-actions1
  pull_request:
    branches:
    - gh-actions1

jobs:
  build-job:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: 3.10
        architect
    - name: Prepare
      run: ./scripts/scripts.sh setup
    - name: Build
      run: ./scripts/scripts.sh build


