name: github workflow

on:
  workflow_dispatch:
  push:
    branches:
    - gh-actions1
  pull_request:
    branches:
    - gh-actions1

jobs:
  build-job:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'
        cache: 'pip'
        architecture: 'x86'
    - name: Prepare
      run: ./scripts/scripts.sh setup
    - name: Build
      run: ./scripts/scripts.sh build


