name: release

on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build-job:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 
      uses: actions/setup-python@master
      with:
        python-version: '3.10'
        architecture: 'x64'
        cache: 'pip'
    - name: Prepare
      run: ./scripts/script.sh setup
    - name: Build
      run: ./scripts/script.sh build
    - name: Release
      uses: docker://antonyurchenko/git-release:v5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: |
            build_linux/*.deb


